feat: login via course platform with default password
ymzhang-cs/BJTU-Homework-Tracker pull request #6
Opened 2024-11-20 15:09 UTC by ram6ert

2024-11-20 15:19 UTC, hewkick commented
好快的写

2024-11-20 15:20 UTC, ram6ert commented
close #5 :D

2024-11-20 15:21 UTC, ram6ert commented
> 好快的写

刚刚写的

2024-11-20 16:06 UTC, ymzhang-cs commented
好厉害！！

2024-11-20 16:11 UTC, ymzhang-cs requested changes
谢谢大佬提pr！还有几个小地方想探讨一下~

2024-11-20 16:11 UTC, ymzhang-cs commented on Login/cp.py
> +            'password': hashlib.md5(f'Bjtu@{student_id}'.encode()).hexdigest(),
这里让用户输入密码或许会更好？可以在config里提醒用户默认密码

2024-11-20 16:11 UTC, ymzhang-cs commented on config_sample.yaml
> +  cp:
可以在这里让用户填写password

2024-11-20 16:11 UTC, ymzhang-cs commented on run.py
> +        my_login.login(**(login_args or {}))
这里是不是和 `login_args = config['login'].get(login_method, {})` 功能重复啦？

2024-11-20 16:14 UTC, ram6ert commented on config_sample.yaml
> +  cp:
明文写password不太好，可以写password的md5

2024-11-20 16:18 UTC, ram6ert commented on run.py
> +        my_login.login(**(login_args or {}))
是，一开始以为是None的问题，后来发现dict读不到就会KeyError，后面就忘改了。

2024-11-20 16:22 UTC, ymzhang-cs commented on config_sample.yaml
> +  cp:
不过在本地应该还好？可以给两个选项这样的，用户选择提供明文还是md5

2024-11-20 16:27 UTC, ram6ert commented on Login/cp.py
> +            'password': hashlib.md5(f'Bjtu@{student_id}'.encode()).hexdigest(),
但其实学生不能更改自己在智慧平台的密码🤓

2024-11-20 16:29 UTC, ram6ert commented on Login/cp.py
> +            'password': hashlib.md5(f'Bjtu@{student_id}'.encode()).hexdigest(),
我搞错了，是可以更改的，但要登录后才能修改，待我调整

2024-11-20 16:39 UTC, ram6ert commented
稍作了一下修改，但是没实现用户在交互界面输入密码的功能，明天再说…😴

2024-11-22 02:36 UTC, ram6ert commented
rebase了一下，顺便试验了一下签名，然后强制推送了（

2024-11-22 07:17 UTC, ymzhang-cs approved these changes
好赞好赞🥰🥰🥰

2024-11-22 07:20 UTC, merged